on:
    workflow_dispatch
    # push:
    # ...
  
name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        env:
            TARGET: "nerdear.la/en/"
            RECURSIVE: true
